### ISSUE TITLE
Logos that are uploaded are often stretched and distorted 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#116]
**Describe the bug**  
Logos that are not a pre defined limited size when uploaded are often stretched and distorted 

**To Reproduce**  
1. Go to theme options
2. Header 
3. Upload a logo that is not 2167 by 918 pixels (867 by 200)

**Expected behavior**  
expect the logo to have a fixed height but the width to expand and contract with the aspect ratio of the image 

**Actual behavior**  
The height and width are both fixed so the image is stretch to match 

**Link to a page where the bug is reproduced in isolation (optional)**  
URL so we can quickly see the issue 

**Screenshots**  
Add screenshots or preferably a video / gif to help explain your problem.

**Platform:**  
Paste link from here https://www.whatsmybrowser.org/ 

**Additional context**  
we now have 4 sites with a custom logo

**Comment by AmnestyAM** [comment]
opened from this -> https://github.com/amnestywebsite/humanity-theme/discussions/57

**Comment by jonmcp** [comment]
The available space for logos has an aspect ratio of 5:2 (180x72) because we constrain the width of that area.

For an extra-wide (or extra-tall) logo, this results in a scaled-down version of the image being used, in which both dimensions are smaller than (or equal to) this available space.
These images are then stretched to fit vertically but, because of the width constraint, they're ending up being squashed.

A partial fix would remove the restriction on the width, and remove the vertical stretch too, so that the images' aspect ratio can be respected.
Whilst this would improve the appearance of some logos, full colour logos may still look a little odd.
A more robust fix would _also_ involve changing the image size itself, in which we remove the width constraint, and downsize specifically on the height. 
However, this would mean that the logo would need uploading again, so that the correct image size is generated.

**Comment by AmnestyAM** [comment]
I am happy to upload the new logos on all the sites when we release

**Comment by AmnestyAM** [comment]
I am testing the above here -> https://istechstg.wpengine.com/

With this logo

![Image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/08ca79d2-3015-4926-a617-5e62d9c81e77)

The logo still looks blurry, my guess is I uploaded something too wide

![Image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/69002bf1-949a-408e-aefb-3b8615a39ebf)

![Image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/9036acdd-5164-4b60-92f0-6667a991755e)

not needed for this ticket but it would be nice to say in the CMS if there are any rules for the logo in the UI, ie X by Y only or not grater that X or Y etc

**Comment by AmnestyAM** [comment]
Looks ok on PRD STG so we are guessing its a GIT issue on SL site 

![Image](https://github.com/amnestywebsite/humanity-theme/assets/37809410/17bbdf09-16a7-4cc5-879b-aaf70028cabb)
