### ISSUE TITLE
Bug - [new Page] - no templates when creating new pages

### ISSUE THREAD

**Issue by Gudnith** [amnestywebsite/humanity-theme#311]
**Describe the bug**  
I want to create a page with the template 'page-petitions.php' to setup a page like https://www.amnesty.org/en/get-involved/take-action/ except there are no templates available and it defaults to the index one.

**To Reproduce**  
Create a new page and try to pick a template for it

**Expected behaviour**  
A list of available templates shows up

**Actual behaviour**  
I'm not able to pick a template to use
![Screenshot 2024-07-22 110644](https://github.com/user-attachments/assets/a3a7a540-d512-453c-85b4-e75c584870c1)

**Platform:**  
[Paste link from here https://www.whatsmybrowser.org/ ](https://www.whatsmybrowser.org/b/CM5QH)

**Additional context**  
This is reproducible by creating a new wordpress installation and setting up the humanity theme and dependencies.

**Comment by AmnestyAM** [comment]
I couldn't replicate this in our infrastructure, on our test site, I recommended setting the template in the database for the post.

**Comment by Gudnith** [comment]
This is a issue when running wordpress 6.6.1 on 6.4.5 it works as expected

**Comment by AmnestyAM** [comment]
We will be able to resolve this when we get around to making the theme compatible to 6.6.* which should be pretty soon, we are now taking the approach to support features which makes us a little slower at supporting new versions of WordPress, previously we were supporting a lot quicker but disabling features.

**Comment by jaymcp** [comment]
Hey folks, a quick update on this. We brought forward the 6.6 compatibility work, and are currently working on it. It's tracked in #365. 

I can confirm that the reason templates aren't available in later versions of WordPress is because WordPress have decided to drop support for PHP templates, which means that hybrid themes are no longer feasible. So we're working on replacing our PHP templates with HTML templates that are compatible with more recent versions of WordPress.

**Comment by jaymcp** [comment]
the latest release of the theme now supports WP 6.6, so this issue should be resolved.
