### ISSUE TITLE
Bug - Search - Taxonomy filters not working

### ISSUE THREAD

**Issue by SophieAmnesty** [amnestywebsite/humanity-theme#449]
**Describe the bug**  
When I use the filters on the search page, they don't seem to be working. 

**To Reproduce**  
1. Go to https://www.amnesty.org/en/search/. The full list with no filters shows 21,111 results
2. Add a filter (content type, country, resource type or topic). E.g. content type: education: https://www.amnesty.org/en/search/?qcategory=2132 
3. see results still show the full list of 21,111 results.

**Expected behaviour**  
The filters should show a sub-section of the results, i.e. the content which has the relevant tag. 

**Actual behaviour**  
Some of the filters don't seem to be having the normal filtering effect. 

**Link to a page where the bug is reproduced in isolation (optional)**  
https://www.amnesty.org/en/search/?qcategory=2132

**Screenshots**  
![image](https://github.com/user-attachments/assets/c8aeb10f-cac8-4ef5-ac9c-c4177e8c87df)

**Platform:**  
https://www.whatsmybrowser.org/b/UILZ7

**Additional context** 
The filters for Year and Month seem to be working

**Comment by jaymcp** [comment]
@carolinejcourtney @SophieAmnesty this fix is now available on STG. Could I ask you to take a look and check whether you're happy with it, please?
Once checked, please remove the `UAT required` label.
If it passes muster, please add the `UAT approved` label; otherwise, please add the `UAT feedback` label, and let me know where/how it fails.
